apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-proj
  labels:
    app: capstone-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-proj
  template:
    metadata:
      labels:
        app: capstone-proj
    spec:
      containers:
        - image: niceday2256/capstone-proj:latest
          name: capstone-proj
          ports:
            - name: web
              containerPort: 80